### ISSUE TITLE
JIRA button does not show (both Chrome & Firefox)

### ISSUE THREAD

**Issue by nicooorts** [Teamweek/browser-extension#64]
Since a few weeks the Toggl Plan button stopped working on JIRA Cloud. It still works on Trello, bitbucket, github,...

tested both with Chrome and Firefox extension

**Comment by kelonye** [comment]
Hey there. Noted ... fixing this in a few ...

**Comment by nicooorts** [comment]
@kelonye any news on this one?

**Comment by kelonye** [comment]
@nicooorts hey. i've pushed an update with a fix for jira.

**Comment by nicooorts** [comment]
It works! Thx for the update
